Repository ets-ninja/frontend, pull requests merged in 2022-10, with the labels that each got.

#25 Updated auth flow
  package-lock.json
  package.json
  src/components/Layout/Header/Header.jsx
  src/components/ProtectedRoute.jsx
  src/components/UIElements/ErrorMessage.js
  src/components/forms/LoginForm.js
  src/index.js
  src/pages/Profile/Profile.jsx
  src/redux/auth/authActions.js
  src/redux/auth/authPersistConfig.js
  src/redux/auth/authSlice.js
  src/redux/modal/modalConfig.js
  src/redux/store.js
  src/redux/user/userActions.js
  src/redux/user/userConfig.js
  src/redux/user/userSlice.js
  src/services/axios/index.js
  src/services/axios/user.js
Labels: ready to merge

#27 Intro page
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/assets/tempImages/monetka.png
  src/assets/tempImages/swiperPic1.png
  src/assets/tempImages/swiperPic2.png
  src/assets/tempImages/swiperPic3.png
  src/assets/tempImages/swiperPic4.png
  src/assets/tempImages/swiperPic5.png
  src/modal/PublicJarModal.jsx
  src/modal/index.js
  src/pages/Dashboard.jsx
  src/pages/IntoPage/IntroSwiper.jsx
Labels: ready to merge

#29 fix bug with update user photo
  src/modal/UpdatePhotoModal/UpdatePhotoModal.jsx
  src/pages/Profile/Profile.jsx
  src/redux/user/userActions.js
Labels: ready to merge

#31 Nikita/notifications init
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/App.js
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Header/Notification.jsx
  src/components/Layout/Layout.jsx
  src/components/UIElements/NotificationToast.jsx
  src/components/forms/RegistrationForm.js
  src/firebase.js
  src/redux/auth/authActions.js
  src/redux/notifications/notificationActions.js
  src/redux/notifications/notificationConfig.js
  src/redux/notifications/notificationSlice.js
  src/redux/store.js
  src/redux/user/userActions.js
  src/redux/user/userSlice.js
Labels: ready to merge

#30 Myroslav/jar card
  package-lock.json
  package.json
  src/App.js
  src/components/JarCard/JarCard.jsx
  src/components/JarCard/images/JarStep1.png
  src/components/JarCard/images/JarStep2.png
  src/components/JarCard/images/JarStep3.png
  src/components/JarCard/images/JarStep4.png
  src/components/JarCard/images/JarStep5.png
  src/components/JarCard/images/JarStep6.png
  src/components/JarCard/index.js
  src/components/JarCard/jarStepHandler.js
  src/components/Layout/Layout.jsx
  src/modal/PublicJarModal.jsx
  src/pages/PublicPage.jsx
Labels: ready to merge, conflicts resolved

#26 Yuliia/wishlist page
  src/components/BasicPagination.jsx
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/WishlistCard.jsx
  src/components/styled/ResponsiveContainer.jsx
  src/components/styled/StyledDropDownMenu.jsx
  src/modal/UpdatePhotoModal/UpdatePhotoModal.jsx
  src/pages/Dashboard.jsx
  src/pages/Wishlist.jsx
  src/redux/store.js
  src/redux/wishlist/wishlistActions.js
  src/redux/wishlist/wishlistConfig.js
  src/redux/wishlist/wishlistSlice.js
Labels: ready to merge

#32 Myroslav/public page
  src/App.js
  src/components/JarCard/JarCard.jsx
  src/components/Layout/Header/Header.jsx
  src/components/publicPage/CardSkeleton.jsx
  src/components/publicPage/FilterForm.jsx
  src/components/publicPage/SliderItemsPerPage.jsx
  src/components/publicPage/UserCard.jsx
  src/components/publicPage/index.js
  src/modal/PublicJarModal.jsx
  src/pages/PublicPage.jsx
  src/redux/public/publicActions.js
  src/redux/public/publicSelectors.js
  src/redux/public/publicSlice.js
  src/redux/store.js
Labels: ready to merge

#34 Nikita/snackbars
  src/components/Layout/Layout.jsx
  src/components/UIElements/SnackBars/ErrorMessage.jsx
  src/components/UIElements/SnackBars/InfoMessage.jsx
  src/components/UIElements/SnackBars/NotificationToast.jsx
  src/components/UIElements/SnackBars/SuccessMessage.jsx
  src/components/forms/Stripe/SetupForm.jsx
  src/redux/request/requestAction.js
  src/redux/request/requestSlice.js
  src/redux/snackbar/README.md
  src/redux/snackbar/snackbarSlice.js
  src/redux/store.js
  src/services/axios/index.js
Labels: enhancement, ready to merge

#35 Bogd/creation page
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/assets/swinka.png
  src/components/CreationResult.jsx
  src/components/NumField.jsx
  src/components/UIElements/BasketDashboardHeader.jsx
  src/components/UIElements/SnackBars/ErrorMessage.jsx
  src/components/UIElements/SnackBars/SuccessMessage.jsx
  src/components/forms/CreationForm.jsx
  src/components/forms/CreationForm2.jsx
  src/components/forms/CreationForm3.jsx
  src/modal/UpdatePhotoModal/UpdatePhotoModal.jsx
  src/pages/CreationPage.jsx
  src/redux/basket/createBasketSlice.js
  src/redux/store.js
  src/redux/user/userActions.js
  src/redux/user/userSlice.js
Labels: waiting for review, ready to merge, conflicts resolved

#37 Nikita/notifications
  public/firebase-messaging-sw.js
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Header/Notification.jsx
  src/components/UIElements/SnackBars/NotificationToast.jsx
  src/firebase.js
  src/redux/notifications/notificationActions.js
  src/redux/notifications/notificationSlice.js
  src/utils/notification/loadBackgroundMessages.js
  src/utils/notification/notificationChannel.js
  src/utils/notification/removeSeenNotification.js
Labels: ready to merge

#33 Confirm email feature, updated auth, sing-in flows
  craco.config.js
  package-lock.json
  package.json
  src/App.js
  src/components/Layout/Header/Header.jsx
  src/components/forms/ConfirmEmailForm.js
  src/components/forms/LoginForm.js
  src/components/forms/RegistrationForm.js
  src/index.js
  src/pages/Register/ConfirmEmail.jsx
  src/pages/Register/Register.jsx
  src/redux/auth/authActions.js
  src/redux/auth/authSlice.js
  src/redux/store.js
  src/redux/user/userActions.js
  src/redux/user/userSlice.js
Labels: ready to merge

#38 Myroslav/public page
  src/components/JarCard/JarCard.jsx
  src/components/JarCard/utils/index.js
  src/components/JarCard/utils/jarStepHandler.js
  src/components/JarCard/utils/transformTransactionTime.js
  src/components/Layout/Layout.jsx
  src/components/SumLinearProgress.jsx
  src/components/publicPage/CardSkeleton.jsx
  src/components/publicPage/FilterForm.jsx
  src/components/publicPage/SettingsBar.jsx
  src/components/publicPage/SliderItemsPerPage.jsx
  src/components/publicPage/UserCard.jsx
  src/components/publicPage/index.js
  src/modal/PublicJarModal.jsx
  src/modal/index.js
  src/pages/IntoPage/IntroSwiper.jsx
  src/pages/PublicPage.jsx
Labels: ready to merge

#39 Refactored axios interceptors, removed comments
  src/services/axios/index.js
  src/services/axios/user.js
Labels: ready to merge

#41 Updated header and footer
  src/components/Layout/Footer/Footer.jsx
  src/components/Layout/Header/Header.jsx
Labels: ready to merge

#36 Yuliia/wishlist page main logic
  src/App.js
  src/App.scss
  src/assets/noImage.png
  src/components/BasicPagination.jsx
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/UIElements/SnackBars/SuccessMessage.jsx
  src/components/WishlistCard.jsx
  src/components/WishlistItemStepper.jsx
  src/components/forms/CreationForm3.jsx
  src/modal/DeleteWishlistItemModal.jsx
  src/modal/UpdatePhotoModal/UpdatePhotoModal.jsx
  src/modal/index.js
  src/pages/CreateWishlistItem.jsx
  src/pages/CreationPage.jsx
  src/pages/Wishlist.jsx
  src/pages/WishlistItem.jsx
  src/redux/basket/createBasketSlice.js
  src/redux/store.js
  src/redux/wishlist/wishlistActions.js
  src/redux/wishlist/wishlistConfig.js
  src/redux/wishlist/wishlistSlice.js
Labels: ready to merge

#42 Reset pic design, added field limits, changed UAH to USD.
  src/components/NumField.jsx
  src/components/forms/CreationForm.jsx
  src/components/forms/CreationForm2.jsx
  src/components/forms/CreationForm3.jsx
  src/pages/CreationPage.jsx
  src/redux/basket/createBasketSlice.js
Labels: ready to merge

#46 Added 404 page , Reworked creation forms
  src/App.js
  src/components/NotFound.jsx
  src/components/forms/CreationForm2.jsx
  src/components/forms/CreationForm3.jsx
  src/pages/CreationPage.jsx
Labels: ready to merge

#47 Bogd1y/saving schemes UI
  src/pages/SavingsSchemes.jsx
Labels: ready to merge

#48 Yuliia/wishlist fix
  src/components/WishlistCard.jsx
  src/modal/DeleteWishlistItemModal.jsx
  src/modal/UpdatePhotoModal/UpdatePhotoModal.jsx
  src/modal/index.js
  src/pages/Wishlist.jsx
  src/pages/WishlistItem.jsx
  src/redux/wishlist/wishlistSlice.js
Labels: ready to merge

#49 Stripe
  src/components/forms/Stripe/DonateForm.jsx
Labels: ready to merge

#50 Finished dedicated jar page and dashboard
  package-lock.json
  package.json
  src/App.js
  src/components/Charts/BasketChart.js
  src/components/Charts/BasketChart.jsx
  src/components/Charts/JarTransactionList.jsx
  src/components/Dashboard/JarDashboard.jsx
  src/components/Dashboard/JarDashboardHeader.jsx
  src/components/JarCard/JarCard.jsx
  src/components/JarPage/JarDescription.jsx
  src/components/JarPage/JarInfo.jsx
  src/components/JarPage/JarInfoHeader.jsx
  src/components/JarPage/JarProgress.jsx
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Stripe/DonateLogic/DonateIndex.jsx
  src/components/Stripe/ReceiveLogic/ReceiveIndex.jsx
  src/components/SumLinearProgress.jsx
  src/components/UIElements/BasketBox.jsx
  src/components/UIElements/BasketDashboard.jsx
  src/components/UIElements/BasketDashboardHeader.jsx
  src/components/UIElements/LoadingSpinner.jsx
  src/components/forms/CreationForm.jsx
  src/components/forms/CreationForm2.jsx
  src/components/forms/CreationForm3.jsx
  src/components/forms/Stripe/DonateForm.jsx
  src/modal/UpdateJarModal.jsx
  src/modal/UpdatePhotoModal/UpdatePhotoModal.jsx
  src/pages/Basket.jsx
  src/pages/CreationPage.jsx
  src/pages/Dashboard.jsx
  src/pages/JarPage.jsx
  src/pages/PublicPage.jsx
  src/pages/WishlistItem.jsx
  src/redux/jar/basketActions.js
  src/redux/jar/basketSlice.js
  src/redux/jar/createBasketSlice.js
  src/redux/store.js
Labels: ready to merge

#53 notifications v3
  .github/workflows/deploy.yml
  public/firebase-messaging-sw.js
  src/App.js
  src/components/Layout/Header/Header.jsx
  src/components/Layout/Header/Notifications.jsx
  src/components/UIElements/SnackBars/NotificationToast.jsx
  src/firebase.js
  src/redux/notifications/notificationActions.js
  src/redux/notifications/notificationSlice.js
  src/redux/user/userSlice.js
Labels: ready to merge

#55 hot fix snackbars
  src/components/UIElements/SnackBars/ErrorMessage.jsx
  src/components/UIElements/SnackBars/InfoMessage.jsx
  src/components/UIElements/SnackBars/SuccessMessage.jsx
Labels: ready to merge

#56 deploy config
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  firebase.json
  package.json
Labels: waiting for review

#54 add compress image
  package.json
  src/App.js
  src/components/forms/LoginForm.js
  src/modal/UpdatePhotoModal/UpdatePhotoModal.jsx
  src/pages/Profile/Profile.jsx
  src/pages/PublicPage.jsx
Labels: waiting for review

#51 Myroslav/public page
  package-lock.json
  src/App.js
  src/components/Dashboard/JarDashboard.jsx
  src/components/Dashboard/JarDashboardHeader.jsx
  src/components/JarCard/JarCard.jsx
  src/components/JarPage/JarDescription.jsx
  src/components/UIElements/LoadingSpinner.jsx
  src/components/forms/CreationForm3.jsx
  src/components/forms/Stripe/DonateForm.jsx
  src/components/publicPage/SettingsBar.jsx
  src/components/publicPage/SliderItemsPerPage.jsx
  src/components/publicPage/UserCard.jsx
  src/hooks/useModal.js
  src/modal/PublicJarModal/PublicJarModal.jsx
  src/modal/PublicJarModal/index.js
  src/modal/UpdateJarModal.jsx
  src/modal/index.js
  src/pages/IntoPage/IntroSwiper.jsx
  src/pages/PublicPage.jsx
  src/redux/modal/modalActions.js
  src/redux/modal/modalConfig.js
  src/redux/modal/modalSelectors.js
  src/redux/modal/modalSlice.js
Labels: ready to merge, conflicts resolved
